version: '2'

services:
  migration:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "--migration true"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDR=cache
      - REDIS_PORT=6379
      - DB_USER=prism
      - DB_PASSWORD=password
      - DB_NAME=prism_api
      - DB_PORT=3306
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
  
  cache:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=prism
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=prism_api
      - TZ=Asia/Tokyo
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
      
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  db: