version: '2'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDR=cache
      - REDIS_PORT=6379
      - DB_USER=prism
      - DB_PASSWORD=C9UxGe3ctRvSDJ56
      - DB_NAME=prism_api
      - DB_PORT=3306
      - DB_HOST=db
    healthcheck:
      test: ["CMD", "/bin/healthcheck"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s
    depends_on:
      cache:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  migration:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "--migration true"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDR=cache
      - REDIS_PORT=6379
      - DB_USER=prism
      - DB_PASSWORD=C9UxGe3ctRvSDJ56
      - DB_NAME=prism_api
      - DB_PORT=3306
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
  
  cache:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 30
      start_period: 5s

  db:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Xj2qXnaTZ4gvj5Dp
      - MYSQL_USER=prism
      - MYSQL_PASSWORD=C9UxGe3ctRvSDJ56
      - MYSQL_DATABASE=prism_api
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s


  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  db: