version: '2'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CACHE_ADDR=cache:6379
  
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"