// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scarlet0725/prism-api/ent/googleoauthtoken"
	"github.com/scarlet0725/prism-api/ent/user"
)

// GoogleOauthTokenCreate is the builder for creating a GoogleOauthToken entity.
type GoogleOauthTokenCreate struct {
	config
	mutation *GoogleOauthTokenMutation
	hooks    []Hook
}

// SetRefreshToken sets the "refresh_token" field.
func (gotc *GoogleOauthTokenCreate) SetRefreshToken(s string) *GoogleOauthTokenCreate {
	gotc.mutation.SetRefreshToken(s)
	return gotc
}

// SetAccessToken sets the "access_token" field.
func (gotc *GoogleOauthTokenCreate) SetAccessToken(s string) *GoogleOauthTokenCreate {
	gotc.mutation.SetAccessToken(s)
	return gotc
}

// SetExpiry sets the "expiry" field.
func (gotc *GoogleOauthTokenCreate) SetExpiry(t time.Time) *GoogleOauthTokenCreate {
	gotc.mutation.SetExpiry(t)
	return gotc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (gotc *GoogleOauthTokenCreate) SetUserID(id int) *GoogleOauthTokenCreate {
	gotc.mutation.SetUserID(id)
	return gotc
}

// SetUser sets the "user" edge to the User entity.
func (gotc *GoogleOauthTokenCreate) SetUser(u *User) *GoogleOauthTokenCreate {
	return gotc.SetUserID(u.ID)
}

// Mutation returns the GoogleOauthTokenMutation object of the builder.
func (gotc *GoogleOauthTokenCreate) Mutation() *GoogleOauthTokenMutation {
	return gotc.mutation
}

// Save creates the GoogleOauthToken in the database.
func (gotc *GoogleOauthTokenCreate) Save(ctx context.Context) (*GoogleOauthToken, error) {
	return withHooks[*GoogleOauthToken, GoogleOauthTokenMutation](ctx, gotc.sqlSave, gotc.mutation, gotc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gotc *GoogleOauthTokenCreate) SaveX(ctx context.Context) *GoogleOauthToken {
	v, err := gotc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gotc *GoogleOauthTokenCreate) Exec(ctx context.Context) error {
	_, err := gotc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gotc *GoogleOauthTokenCreate) ExecX(ctx context.Context) {
	if err := gotc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gotc *GoogleOauthTokenCreate) check() error {
	if _, ok := gotc.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`ent: missing required field "GoogleOauthToken.refresh_token"`)}
	}
	if _, ok := gotc.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "GoogleOauthToken.access_token"`)}
	}
	if _, ok := gotc.mutation.Expiry(); !ok {
		return &ValidationError{Name: "expiry", err: errors.New(`ent: missing required field "GoogleOauthToken.expiry"`)}
	}
	if _, ok := gotc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "GoogleOauthToken.user"`)}
	}
	return nil
}

func (gotc *GoogleOauthTokenCreate) sqlSave(ctx context.Context) (*GoogleOauthToken, error) {
	if err := gotc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gotc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gotc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gotc.mutation.id = &_node.ID
	gotc.mutation.done = true
	return _node, nil
}

func (gotc *GoogleOauthTokenCreate) createSpec() (*GoogleOauthToken, *sqlgraph.CreateSpec) {
	var (
		_node = &GoogleOauthToken{config: gotc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: googleoauthtoken.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: googleoauthtoken.FieldID,
			},
		}
	)
	if value, ok := gotc.mutation.RefreshToken(); ok {
		_spec.SetField(googleoauthtoken.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := gotc.mutation.AccessToken(); ok {
		_spec.SetField(googleoauthtoken.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := gotc.mutation.Expiry(); ok {
		_spec.SetField(googleoauthtoken.FieldExpiry, field.TypeTime, value)
		_node.Expiry = value
	}
	if nodes := gotc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   googleoauthtoken.UserTable,
			Columns: []string{googleoauthtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_google_oauth_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GoogleOauthTokenCreateBulk is the builder for creating many GoogleOauthToken entities in bulk.
type GoogleOauthTokenCreateBulk struct {
	config
	builders []*GoogleOauthTokenCreate
}

// Save creates the GoogleOauthToken entities in the database.
func (gotcb *GoogleOauthTokenCreateBulk) Save(ctx context.Context) ([]*GoogleOauthToken, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gotcb.builders))
	nodes := make([]*GoogleOauthToken, len(gotcb.builders))
	mutators := make([]Mutator, len(gotcb.builders))
	for i := range gotcb.builders {
		func(i int, root context.Context) {
			builder := gotcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoogleOauthTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gotcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gotcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gotcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gotcb *GoogleOauthTokenCreateBulk) SaveX(ctx context.Context) []*GoogleOauthToken {
	v, err := gotcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gotcb *GoogleOauthTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := gotcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gotcb *GoogleOauthTokenCreateBulk) ExecX(ctx context.Context) {
	if err := gotcb.Exec(ctx); err != nil {
		panic(err)
	}
}
