// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/scarlet0725/prism-api/ent/event"
	"github.com/scarlet0725/prism-api/ent/ryzmevent"
)

// RyzmEvent is the model entity for the RyzmEvent schema.
type RyzmEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID string `json:"uuid,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RyzmEventQuery when eager-loading is set.
	Edges                     RyzmEventEdges `json:"edges"`
	event_related_ryzm_events *int
}

// RyzmEventEdges holds the relations/edges for other nodes in the graph.
type RyzmEventEdges struct {
	// Event holds the value of the event edge.
	Event *Event `json:"event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RyzmEventEdges) EventOrErr() (*Event, error) {
	if e.loadedTypes[0] {
		if e.Event == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: event.Label}
		}
		return e.Event, nil
	}
	return nil, &NotLoadedError{edge: "event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RyzmEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ryzmevent.FieldID:
			values[i] = new(sql.NullInt64)
		case ryzmevent.FieldUUID:
			values[i] = new(sql.NullString)
		case ryzmevent.ForeignKeys[0]: // event_related_ryzm_events
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type RyzmEvent", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RyzmEvent fields.
func (re *RyzmEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ryzmevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			re.ID = int(value.Int64)
		case ryzmevent.FieldUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value.Valid {
				re.UUID = value.String
			}
		case ryzmevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field event_related_ryzm_events", value)
			} else if value.Valid {
				re.event_related_ryzm_events = new(int)
				*re.event_related_ryzm_events = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryEvent queries the "event" edge of the RyzmEvent entity.
func (re *RyzmEvent) QueryEvent() *EventQuery {
	return (&RyzmEventClient{config: re.config}).QueryEvent(re)
}

// Update returns a builder for updating this RyzmEvent.
// Note that you need to call RyzmEvent.Unwrap() before calling this method if this RyzmEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (re *RyzmEvent) Update() *RyzmEventUpdateOne {
	return (&RyzmEventClient{config: re.config}).UpdateOne(re)
}

// Unwrap unwraps the RyzmEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (re *RyzmEvent) Unwrap() *RyzmEvent {
	_tx, ok := re.config.driver.(*txDriver)
	if !ok {
		panic("ent: RyzmEvent is not a transactional entity")
	}
	re.config.driver = _tx.drv
	return re
}

// String implements the fmt.Stringer.
func (re *RyzmEvent) String() string {
	var builder strings.Builder
	builder.WriteString("RyzmEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", re.ID))
	builder.WriteString("uuid=")
	builder.WriteString(re.UUID)
	builder.WriteByte(')')
	return builder.String()
}

// RyzmEvents is a parsable slice of RyzmEvent.
type RyzmEvents []*RyzmEvent

func (re RyzmEvents) config(cfg config) {
	for _i := range re {
		re[_i].config = cfg
	}
}
