// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scarlet0725/prism-api/ent/event"
	"github.com/scarlet0725/prism-api/ent/predicate"
	"github.com/scarlet0725/prism-api/ent/ryzmevent"
)

// RyzmEventQuery is the builder for querying RyzmEvent entities.
type RyzmEventQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.RyzmEvent
	withEvent  *EventQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RyzmEventQuery builder.
func (req *RyzmEventQuery) Where(ps ...predicate.RyzmEvent) *RyzmEventQuery {
	req.predicates = append(req.predicates, ps...)
	return req
}

// Limit the number of records to be returned by this query.
func (req *RyzmEventQuery) Limit(limit int) *RyzmEventQuery {
	req.limit = &limit
	return req
}

// Offset to start from.
func (req *RyzmEventQuery) Offset(offset int) *RyzmEventQuery {
	req.offset = &offset
	return req
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (req *RyzmEventQuery) Unique(unique bool) *RyzmEventQuery {
	req.unique = &unique
	return req
}

// Order specifies how the records should be ordered.
func (req *RyzmEventQuery) Order(o ...OrderFunc) *RyzmEventQuery {
	req.order = append(req.order, o...)
	return req
}

// QueryEvent chains the current query on the "event" edge.
func (req *RyzmEventQuery) QueryEvent() *EventQuery {
	query := (&EventClient{config: req.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := req.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := req.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ryzmevent.Table, ryzmevent.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ryzmevent.EventTable, ryzmevent.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(req.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RyzmEvent entity from the query.
// Returns a *NotFoundError when no RyzmEvent was found.
func (req *RyzmEventQuery) First(ctx context.Context) (*RyzmEvent, error) {
	nodes, err := req.Limit(1).All(newQueryContext(ctx, TypeRyzmEvent, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ryzmevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (req *RyzmEventQuery) FirstX(ctx context.Context) *RyzmEvent {
	node, err := req.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RyzmEvent ID from the query.
// Returns a *NotFoundError when no RyzmEvent ID was found.
func (req *RyzmEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = req.Limit(1).IDs(newQueryContext(ctx, TypeRyzmEvent, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ryzmevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (req *RyzmEventQuery) FirstIDX(ctx context.Context) int {
	id, err := req.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RyzmEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RyzmEvent entity is found.
// Returns a *NotFoundError when no RyzmEvent entities are found.
func (req *RyzmEventQuery) Only(ctx context.Context) (*RyzmEvent, error) {
	nodes, err := req.Limit(2).All(newQueryContext(ctx, TypeRyzmEvent, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ryzmevent.Label}
	default:
		return nil, &NotSingularError{ryzmevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (req *RyzmEventQuery) OnlyX(ctx context.Context) *RyzmEvent {
	node, err := req.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RyzmEvent ID in the query.
// Returns a *NotSingularError when more than one RyzmEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (req *RyzmEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = req.Limit(2).IDs(newQueryContext(ctx, TypeRyzmEvent, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ryzmevent.Label}
	default:
		err = &NotSingularError{ryzmevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (req *RyzmEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := req.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RyzmEvents.
func (req *RyzmEventQuery) All(ctx context.Context) ([]*RyzmEvent, error) {
	ctx = newQueryContext(ctx, TypeRyzmEvent, "All")
	if err := req.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RyzmEvent, *RyzmEventQuery]()
	return withInterceptors[[]*RyzmEvent](ctx, req, qr, req.inters)
}

// AllX is like All, but panics if an error occurs.
func (req *RyzmEventQuery) AllX(ctx context.Context) []*RyzmEvent {
	nodes, err := req.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RyzmEvent IDs.
func (req *RyzmEventQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = newQueryContext(ctx, TypeRyzmEvent, "IDs")
	if err := req.Select(ryzmevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (req *RyzmEventQuery) IDsX(ctx context.Context) []int {
	ids, err := req.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (req *RyzmEventQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeRyzmEvent, "Count")
	if err := req.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, req, querierCount[*RyzmEventQuery](), req.inters)
}

// CountX is like Count, but panics if an error occurs.
func (req *RyzmEventQuery) CountX(ctx context.Context) int {
	count, err := req.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (req *RyzmEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeRyzmEvent, "Exist")
	switch _, err := req.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (req *RyzmEventQuery) ExistX(ctx context.Context) bool {
	exist, err := req.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RyzmEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (req *RyzmEventQuery) Clone() *RyzmEventQuery {
	if req == nil {
		return nil
	}
	return &RyzmEventQuery{
		config:     req.config,
		limit:      req.limit,
		offset:     req.offset,
		order:      append([]OrderFunc{}, req.order...),
		inters:     append([]Interceptor{}, req.inters...),
		predicates: append([]predicate.RyzmEvent{}, req.predicates...),
		withEvent:  req.withEvent.Clone(),
		// clone intermediate query.
		sql:    req.sql.Clone(),
		path:   req.path,
		unique: req.unique,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (req *RyzmEventQuery) WithEvent(opts ...func(*EventQuery)) *RyzmEventQuery {
	query := (&EventClient{config: req.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	req.withEvent = query
	return req
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RyzmEvent.Query().
//		GroupBy(ryzmevent.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (req *RyzmEventQuery) GroupBy(field string, fields ...string) *RyzmEventGroupBy {
	req.fields = append([]string{field}, fields...)
	grbuild := &RyzmEventGroupBy{build: req}
	grbuild.flds = &req.fields
	grbuild.label = ryzmevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//	}
//
//	client.RyzmEvent.Query().
//		Select(ryzmevent.FieldUUID).
//		Scan(ctx, &v)
func (req *RyzmEventQuery) Select(fields ...string) *RyzmEventSelect {
	req.fields = append(req.fields, fields...)
	sbuild := &RyzmEventSelect{RyzmEventQuery: req}
	sbuild.label = ryzmevent.Label
	sbuild.flds, sbuild.scan = &req.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RyzmEventSelect configured with the given aggregations.
func (req *RyzmEventQuery) Aggregate(fns ...AggregateFunc) *RyzmEventSelect {
	return req.Select().Aggregate(fns...)
}

func (req *RyzmEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range req.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, req); err != nil {
				return err
			}
		}
	}
	for _, f := range req.fields {
		if !ryzmevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if req.path != nil {
		prev, err := req.path(ctx)
		if err != nil {
			return err
		}
		req.sql = prev
	}
	return nil
}

func (req *RyzmEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RyzmEvent, error) {
	var (
		nodes       = []*RyzmEvent{}
		withFKs     = req.withFKs
		_spec       = req.querySpec()
		loadedTypes = [1]bool{
			req.withEvent != nil,
		}
	)
	if req.withEvent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, ryzmevent.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RyzmEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RyzmEvent{config: req.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(req.modifiers) > 0 {
		_spec.Modifiers = req.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, req.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := req.withEvent; query != nil {
		if err := req.loadEvent(ctx, query, nodes, nil,
			func(n *RyzmEvent, e *Event) { n.Edges.Event = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (req *RyzmEventQuery) loadEvent(ctx context.Context, query *EventQuery, nodes []*RyzmEvent, init func(*RyzmEvent), assign func(*RyzmEvent, *Event)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RyzmEvent)
	for i := range nodes {
		if nodes[i].event_related_ryzm_events == nil {
			continue
		}
		fk := *nodes[i].event_related_ryzm_events
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(event.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "event_related_ryzm_events" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (req *RyzmEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := req.querySpec()
	if len(req.modifiers) > 0 {
		_spec.Modifiers = req.modifiers
	}
	_spec.Node.Columns = req.fields
	if len(req.fields) > 0 {
		_spec.Unique = req.unique != nil && *req.unique
	}
	return sqlgraph.CountNodes(ctx, req.driver, _spec)
}

func (req *RyzmEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ryzmevent.Table,
			Columns: ryzmevent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ryzmevent.FieldID,
			},
		},
		From:   req.sql,
		Unique: true,
	}
	if unique := req.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := req.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ryzmevent.FieldID)
		for i := range fields {
			if fields[i] != ryzmevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := req.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := req.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := req.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := req.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (req *RyzmEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(req.driver.Dialect())
	t1 := builder.Table(ryzmevent.Table)
	columns := req.fields
	if len(columns) == 0 {
		columns = ryzmevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if req.sql != nil {
		selector = req.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if req.unique != nil && *req.unique {
		selector.Distinct()
	}
	for _, m := range req.modifiers {
		m(selector)
	}
	for _, p := range req.predicates {
		p(selector)
	}
	for _, p := range req.order {
		p(selector)
	}
	if offset := req.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := req.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (req *RyzmEventQuery) Modify(modifiers ...func(s *sql.Selector)) *RyzmEventSelect {
	req.modifiers = append(req.modifiers, modifiers...)
	return req.Select()
}

// RyzmEventGroupBy is the group-by builder for RyzmEvent entities.
type RyzmEventGroupBy struct {
	selector
	build *RyzmEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (regb *RyzmEventGroupBy) Aggregate(fns ...AggregateFunc) *RyzmEventGroupBy {
	regb.fns = append(regb.fns, fns...)
	return regb
}

// Scan applies the selector query and scans the result into the given value.
func (regb *RyzmEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeRyzmEvent, "GroupBy")
	if err := regb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RyzmEventQuery, *RyzmEventGroupBy](ctx, regb.build, regb, regb.build.inters, v)
}

func (regb *RyzmEventGroupBy) sqlScan(ctx context.Context, root *RyzmEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(regb.fns))
	for _, fn := range regb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*regb.flds)+len(regb.fns))
		for _, f := range *regb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*regb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := regb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RyzmEventSelect is the builder for selecting fields of RyzmEvent entities.
type RyzmEventSelect struct {
	*RyzmEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (res *RyzmEventSelect) Aggregate(fns ...AggregateFunc) *RyzmEventSelect {
	res.fns = append(res.fns, fns...)
	return res
}

// Scan applies the selector query and scans the result into the given value.
func (res *RyzmEventSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeRyzmEvent, "Select")
	if err := res.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RyzmEventQuery, *RyzmEventSelect](ctx, res.RyzmEventQuery, res, res.inters, v)
}

func (res *RyzmEventSelect) sqlScan(ctx context.Context, root *RyzmEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(res.fns))
	for _, fn := range res.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*res.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := res.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (res *RyzmEventSelect) Modify(modifiers ...func(s *sql.Selector)) *RyzmEventSelect {
	res.modifiers = append(res.modifiers, modifiers...)
	return res
}
