// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scarlet0725/prism-api/ent/predicate"
	"github.com/scarlet0725/prism-api/ent/unstructuredeventinformation"
)

// UnStructuredEventInformationDelete is the builder for deleting a UnStructuredEventInformation entity.
type UnStructuredEventInformationDelete struct {
	config
	hooks    []Hook
	mutation *UnStructuredEventInformationMutation
}

// Where appends a list predicates to the UnStructuredEventInformationDelete builder.
func (useid *UnStructuredEventInformationDelete) Where(ps ...predicate.UnStructuredEventInformation) *UnStructuredEventInformationDelete {
	useid.mutation.Where(ps...)
	return useid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (useid *UnStructuredEventInformationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, UnStructuredEventInformationMutation](ctx, useid.sqlExec, useid.mutation, useid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (useid *UnStructuredEventInformationDelete) ExecX(ctx context.Context) int {
	n, err := useid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (useid *UnStructuredEventInformationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: unstructuredeventinformation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: unstructuredeventinformation.FieldID,
			},
		},
	}
	if ps := useid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, useid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	useid.mutation.done = true
	return affected, err
}

// UnStructuredEventInformationDeleteOne is the builder for deleting a single UnStructuredEventInformation entity.
type UnStructuredEventInformationDeleteOne struct {
	useid *UnStructuredEventInformationDelete
}

// Exec executes the deletion query.
func (useido *UnStructuredEventInformationDeleteOne) Exec(ctx context.Context) error {
	n, err := useido.useid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{unstructuredeventinformation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (useido *UnStructuredEventInformationDeleteOne) ExecX(ctx context.Context) {
	useido.useid.ExecX(ctx)
}
