name: ci
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registory: ghcr.io
          username: scarlet0725
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get short commit hash
        run: echo tag=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/scarlet0725/prism-api:{{ env.tag }}
          platforms: linux/amd64,linux/arm64