// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artist is the predicate function for artist builders.
type Artist func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// ExternalCalendar is the predicate function for externalcalendar builders.
type ExternalCalendar func(*sql.Selector)

// GoogleOauthToken is the predicate function for googleoauthtoken builders.
type GoogleOauthToken func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Venue is the predicate function for venue builders.
type Venue func(*sql.Selector)
